<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Statistical Analysis – Survey Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-multiple-imputation.html" rel="next">
<link href="./03-psychometric-analysis.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-0de45b8b5f35a93596f1d788d60c4c11.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2002bff06063c072ba3953e28565d1ee.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-statistical-analysis.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistical Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Survey Data Analysis</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Welcome</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro-to-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Intro to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-post-survey-data-preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Post-Survey Data Preparation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-psychometric-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Psychometric Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-statistical-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistical Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-imputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Imputation</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link active" data-scroll-target="#research-questions"><span class="header-section-number">5.1</span> Research Questions</a></li>
  <li><a href="#import-the-data" id="toc-import-the-data" class="nav-link" data-scroll-target="#import-the-data"><span class="header-section-number">5.2</span> Import the Data</a></li>
  <li><a href="#rq1-overall-satisfaction-with-online-courses" id="toc-rq1-overall-satisfaction-with-online-courses" class="nav-link" data-scroll-target="#rq1-overall-satisfaction-with-online-courses"><span class="header-section-number">5.3</span> RQ1: Overall Satisfaction With Online Course(s)</a>
  <ul class="collapse">
  <li><a href="#frequency-table" id="toc-frequency-table" class="nav-link" data-scroll-target="#frequency-table"><span class="header-section-number">5.3.1</span> Frequency Table</a></li>
  <li><a href="#collapsed-summary" id="toc-collapsed-summary" class="nav-link" data-scroll-target="#collapsed-summary"><span class="header-section-number">5.3.2</span> Collapsed Summary</a></li>
  <li><a href="#bar-chart" id="toc-bar-chart" class="nav-link" data-scroll-target="#bar-chart"><span class="header-section-number">5.3.3</span> Bar Chart</a></li>
  </ul></li>
  <li><a href="#rq2-motivation-and-overall-online-learning-experience" id="toc-rq2-motivation-and-overall-online-learning-experience" class="nav-link" data-scroll-target="#rq2-motivation-and-overall-online-learning-experience"><span class="header-section-number">5.4</span> RQ2: Motivation and Overall Online Learning Experience</a>
  <ul class="collapse">
  <li><a href="#cross-tabulation-and-chi-square-test" id="toc-cross-tabulation-and-chi-square-test" class="nav-link" data-scroll-target="#cross-tabulation-and-chi-square-test"><span class="header-section-number">5.4.1</span> Cross-Tabulation and Chi-Square Test</a></li>
  <li><a href="#interpreting-cramers-v" id="toc-interpreting-cramers-v" class="nav-link" data-scroll-target="#interpreting-cramers-v"><span class="header-section-number">5.4.2</span> Interpreting Cramer’s <em>V</em></a></li>
  <li><a href="#stacked-bar-chart" id="toc-stacked-bar-chart" class="nav-link" data-scroll-target="#stacked-bar-chart"><span class="header-section-number">5.4.3</span> Stacked Bar Chart</a></li>
  </ul></li>
  <li><a href="#rq3-likert-item-analysis-technology-comfort" id="toc-rq3-likert-item-analysis-technology-comfort" class="nav-link" data-scroll-target="#rq3-likert-item-analysis-technology-comfort"><span class="header-section-number">5.5</span> RQ3: Likert Item Analysis — Technology Comfort</a>
  <ul class="collapse">
  <li><a href="#select-and-label-the-items" id="toc-select-and-label-the-items" class="nav-link" data-scroll-target="#select-and-label-the-items"><span class="header-section-number">5.5.1</span> Select and Label the Items</a></li>
  <li><a href="#item-level-descriptives-mean-and-sd" id="toc-item-level-descriptives-mean-and-sd" class="nav-link" data-scroll-target="#item-level-descriptives-mean-and-sd"><span class="header-section-number">5.5.2</span> Item-Level Descriptives (Mean and SD)</a></li>
  <li><a href="#convert-to-labeled-factors-and-fit-the-likert-object" id="toc-convert-to-labeled-factors-and-fit-the-likert-object" class="nav-link" data-scroll-target="#convert-to-labeled-factors-and-fit-the-likert-object"><span class="header-section-number">5.5.3</span> Convert to Labeled Factors and Fit the Likert Object</a></li>
  <li><a href="#response-profile-plot" id="toc-response-profile-plot" class="nav-link" data-scroll-target="#response-profile-plot"><span class="header-section-number">5.5.4</span> Response Profile Plot</a></li>
  </ul></li>
  <li><a href="#rq4-logistic-regression-predicting-willingness-to-register-again" id="toc-rq4-logistic-regression-predicting-willingness-to-register-again" class="nav-link" data-scroll-target="#rq4-logistic-regression-predicting-willingness-to-register-again"><span class="header-section-number">5.6</span> RQ4: Logistic Regression — Predicting Willingness to Register Again</a>
  <ul class="collapse">
  <li><a href="#fit-the-logistic-regression-model" id="toc-fit-the-logistic-regression-model" class="nav-link" data-scroll-target="#fit-the-logistic-regression-model"><span class="header-section-number">5.6.1</span> Fit the Logistic Regression Model</a></li>
  <li><a href="#model-summary-table-odds-ratios" id="toc-model-summary-table-odds-ratios" class="nav-link" data-scroll-target="#model-summary-table-odds-ratios"><span class="header-section-number">5.6.2</span> Model Summary Table (Odds Ratios)</a></li>
  <li><a href="#odds-ratio-plot" id="toc-odds-ratio-plot" class="nav-link" data-scroll-target="#odds-ratio-plot"><span class="header-section-number">5.6.3</span> Odds Ratio Plot</a></li>
  </ul></li>
  <li><a href="#summary-what-to-report" id="toc-summary-what-to-report" class="nav-link" data-scroll-target="#summary-what-to-report"><span class="header-section-number">5.7</span> Summary: What to Report</a></li>
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise"><span class="header-section-number">5.8</span> Exercise</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistical Analysis</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This handout uses the <a href="http://edmeasurement.net/5244/2001-survey.html">2001 Learning and Technology Survey</a> for illustration. The survey collected information on students’ technology comfort, online learning experiences, and demographics.</p>
<p>Data source:</p>
<ul>
<li>Survey instrument: http://edmeasurement.net/5244/2001-survey.html</li>
<li>SPSS data: https://raw.githubusercontent.com/Wenchao-Ma/Data/main/EDM2001/2001-data.sav</li>
</ul>
<section id="research-questions" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="research-questions"><span class="header-section-number">5.1</span> Research Questions</h2>
<p>This handout addresses four research questions that progress from simple description to multivariate prediction:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 37%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">#</th>
<th style="text-align: left;">Research Question</th>
<th style="text-align: left;">Analysis Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RQ1</td>
<td style="text-align: left;">Overall, to what extent are students dissatisfied or satisfied with the online course(s) they have taken?</td>
<td style="text-align: left;">Frequency table + bar chart</td>
</tr>
<tr class="even">
<td style="text-align: left;">RQ2</td>
<td style="text-align: left;">Is motivation about using technology tools related to overall online learning experience?</td>
<td style="text-align: left;">Chi-square test + Cramer’s <em>V</em></td>
</tr>
<tr class="odd">
<td style="text-align: left;">RQ3</td>
<td style="text-align: left;">What does the distribution of technology comfort look like across the nine Q1.2 items?</td>
<td style="text-align: left;">Likert response profile</td>
</tr>
<tr class="even">
<td style="text-align: left;">RQ4</td>
<td style="text-align: left;">Which factors predict whether students would consider registering for another online course?</td>
<td style="text-align: left;">Binary logistic regression</td>
</tr>
</tbody>
</table>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run this block ONCE to install all required packages.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># After installation you never need to run it again.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(c("ggplot2", "likert", "scales", "sjPlot"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages at the start of every R session.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)   <span class="co"># creating plots</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(likert)    <span class="co"># Likert response profile plots</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)    <span class="co"># formatting axis labels</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)    <span class="co"># contingency tables and regression output</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="import-the-data" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="import-the-data"><span class="header-section-number">5.2</span> Import the Data</h2>
<p><code>read_sav()</code> reads an SPSS data file — either from your computer or directly from a URL — into a data frame. Recall that a data frame is R’s version of a spreadsheet: rows are respondents, columns are variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the SPSS file directly from the web into a data frame named df</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_sav</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://raw.githubusercontent.com/Wenchao-Ma/Data/main/EDM2001/2001-data.sav"</span>,<span class="at">user_na =</span> <span class="cn">FALSE</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions: rows = respondents, columns = variables</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 721  44</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first six rows</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 44
   q1.1 q1.2a q1.2b q1.2c q1.2d q1.2e q1.2f q1.2g q1.2h q1.2i  q1.3  q1.4  q1.5
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1     4     4     4     4     4     3     2     4     2     2     1     4
2     2     4     4     4     4     4     4     4     4     4     3     1     3
3     2     4     4     4     4     4     4     4     3     3     4     1     3
4     2     4     4     4     4     4     4     3     4     3     2     1     2
5     2     4     4     4     4     4     4     3     3     2     2     1     2
6     1     4     4     4     4     4     4     3     3     3     3     1     3
# ℹ 31 more variables: q1.6 &lt;dbl&gt;, q2.1 &lt;dbl&gt;, q2.2 &lt;dbl&gt;, q2.3 &lt;dbl&gt;,
#   q2.4 &lt;dbl&gt;, q2.5 &lt;dbl&gt;, q2.6a &lt;dbl&gt;, q2.6b &lt;dbl&gt;, q2.6c &lt;dbl&gt;, q2.6d &lt;dbl&gt;,
#   q2.6e &lt;dbl&gt;, q2.6f &lt;dbl&gt;, q2.6g &lt;dbl&gt;, q2.7 &lt;dbl&gt;, q2.8 &lt;dbl&gt;, q2.9 &lt;dbl&gt;,
#   q3.1 &lt;dbl&gt;, q3.2 &lt;dbl&gt;, q3.3 &lt;dbl&gt;, q3.4a &lt;dbl&gt;, q3.4b &lt;dbl&gt;, q3.4c &lt;dbl&gt;,
#   q3.4d &lt;dbl&gt;, q3.4e &lt;dbl&gt;, q3.4f &lt;dbl&gt;, q3.4g &lt;dbl&gt;, q3.5 &lt;dbl&gt;, q4.1 &lt;dbl&gt;,
#   q4.2 &lt;dbl&gt;, q4.3 &lt;dbl&gt;, q4.4 &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="rq1-overall-satisfaction-with-online-courses" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="rq1-overall-satisfaction-with-online-courses"><span class="header-section-number">5.3</span> RQ1: Overall Satisfaction With Online Course(s)</h2>
<p><strong>Question:</strong> Overall, to what extent are students dissatisfied or satisfied with the online course(s) they have taken? (Q2.2, six-point scale)</p>
<p>Q2.2 is a single categorical variable, so we describe its distribution with a frequency table (counts and percentages) and a bar chart.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------------</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Q2.2: Overall, to what extent are you dissatisfied or satisfied</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#        with the online course(s) you have taken?</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#        1 = Completely dissatisfied  ...  6 = Completely satisfied</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------------------------------------------</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>overall_exp_num <span class="ot">&lt;-</span> df<span class="sc">$</span>q2<span class="fl">.2</span>   </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>overall_exp <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>q2<span class="fl">.2</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels  =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels  =</span> <span class="fu">c</span>(</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Completely dissatisfied"</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Mostly dissatisfied"</span>,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Somewhat dissatisfied"</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Somewhat satisfied"</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Mostly satisfied"</span>,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Completely satisfied"</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">ordered =</span> <span class="cn">TRUE</span>   <span class="co"># ordered = TRUE tells R this is an ordinal scale</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="frequency-table" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="frequency-table"><span class="header-section-number">5.3.1</span> Frequency Table</h3>
<p><code>table()</code> counts how many respondents chose each category. <code>prop.table()</code> converts those counts into proportions, which we multiply by 100 to get percentages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>rq1_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>overall_exp)       <span class="co"># raw counts</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>rq1_props  <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(rq1_counts)       <span class="co"># proportions (each / total)</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into a readable data frame</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">response   =</span> <span class="fu">names</span>(rq1_counts),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">count      =</span> <span class="fu">as.integer</span>(rq1_counts),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">proportion =</span> <span class="fu">round</span>(<span class="fu">as.numeric</span>(rq1_props), <span class="dv">3</span>),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">percent    =</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(rq1_props), <span class="dv">1</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 response count proportion percent
1 Completely dissatisfied     4      0.024     2.4
2     Mostly dissatisfied    15      0.088     8.8
3   Somewhat dissatisfied    20      0.118    11.8
4      Somewhat satisfied    41      0.241    24.1
5        Mostly satisfied    68      0.400    40.0
6    Completely satisfied    22      0.129    12.9</code></pre>
</div>
</div>
</section>
<section id="collapsed-summary" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="collapsed-summary"><span class="header-section-number">5.3.2</span> Collapsed Summary</h3>
<p>To simplify reporting we combine the three satisfied categories and the three dissatisfied categories into two groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion who chose "Somewhat satisfied" or higher (codes 4, 5, 6)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>prop_satisfied    <span class="ot">&lt;-</span> <span class="fu">mean</span>(df<span class="sc">$</span>overall_exp_num <span class="sc">&gt;=</span> <span class="dv">4</span>,<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportion who chose "Somewhat dissatisfied" or lower (codes 1, 2, 3)</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>prop_dissatisfied <span class="ot">&lt;-</span> <span class="fu">mean</span>(df<span class="sc">$</span>overall_exp_num <span class="sc">&lt;=</span> <span class="dv">3</span>,<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">group      =</span> <span class="fu">c</span>(<span class="st">"Somewhat or more satisfied"</span>, <span class="st">"Somewhat or more dissatisfied"</span>),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">proportion =</span> <span class="fu">round</span>(<span class="fu">c</span>(prop_satisfied, prop_dissatisfied), <span class="dv">3</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          group proportion
1    Somewhat or more satisfied      0.771
2 Somewhat or more dissatisfied      0.229</code></pre>
</div>
</div>
</section>
<section id="bar-chart" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="bar-chart"><span class="header-section-number">5.3.3</span> Bar Chart</h3>
<p><code>ggplot2</code> builds plots layer by layer. <code>aes()</code> maps variables to visual properties (x axis, y axis). <code>geom_col()</code> draws bars. <code>labs()</code> sets titles and axis labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the frequency table to a data frame for ggplot</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>rq1_plot_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(rq1_counts)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(rq1_plot_df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"overall_exp"</span>, <span class="st">"count"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rq1_plot_df, <span class="fu">aes</span>(<span class="at">x =</span> overall_exp, <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Overall Satisfaction With Online Course(s) (Q2.2)"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x     =</span> <span class="st">"Response category"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y     =</span> <span class="st">"Number of respondents"</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Rotate x-axis labels so they don't overlap</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">20</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-statistical-analysis_files/figure-html/rq1-bar-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="note-box note">
<p><strong>Reporting template (RQ1):</strong></p>
<p>Among respondents with non-missing ratings on overall online-course experience (<span class="math inline">\(N = 170\)</span>), the majority reported positive experiences: 24.1% somewhat satisfied, 40.0% mostly satisfied, and 12.9% completely satisfied (77.1% combined). A smaller proportion reported dissatisfaction: 11.8% somewhat dissatisfied, 8.8% mostly dissatisfied, and 2.4% completely dissatisfied (22.9% combined; see Figure X).</p>
</div>
<div class="note-box exercise">
<p>Check the total number of respondents in 5.5.2? Is it the same as the number of responses in the sample? If not, why might that be?</p>
</div>
<div class="note-box jamovi">
<p>In Jamovi, Analyses -&gt; Exploration -&gt; Descriptives -&gt; select Q2.2 -&gt; check “Frequency tables” and “Bar plot”</p>
</div>
<hr>
</section>
</section>
<section id="rq2-motivation-and-overall-online-learning-experience" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="rq2-motivation-and-overall-online-learning-experience"><span class="header-section-number">5.4</span> RQ2: Motivation and Overall Online Learning Experience</h2>
<p><strong>RQ2:</strong> Is motivation about using technology tools (Q1.3) associated with overall online learning experience (Q2.2)?</p>
<p>Both variables are categorical, so we use a chi-square test of independence to test whether the two variables are related, and Cramer’s V to quantify the strength of that association.</p>
<div class="note-box note">
<p>The chi-square test checks whether the distribution of satisfaction ratings looks the same across all motivation groups. A significant result (<span class="math inline">\(p &lt; .05\)</span>) means the groups differ more than we would expect by chance. A non-significant result means any observed differences are within the range of random variation.</p>
</div>
<section id="cross-tabulation-and-chi-square-test" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="cross-tabulation-and-chi-square-test"><span class="header-section-number">5.4.1</span> Cross-Tabulation and Chi-Square Test</h3>
<p><code>sjPlot::tab_xtab()</code> produces a contingency table, chi-square test, and Cramer’s <em>V</em> in one step. <code>show.row.prc = TRUE</code> displays row percentages, making it easier to compare distributions across motivation groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_xtab</span>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.row      =</span> df<span class="sc">$</span>q1<span class="fl">.3</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">var.col      =</span> df<span class="sc">$</span>overall_exp,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">show.row.prc =</span> <span class="cn">TRUE</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">How would you rate<br>your motiva</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="6">overall_exp</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Completely<br>dissatisfied</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mostly dissatisfied</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Somewhat<br>dissatisfied</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Somewhat satisfied</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mostly satisfied</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Completely satisfied</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">1</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#333399;">40&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#333399;">20&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#333399;">40&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">5</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">2</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#333399;">3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3</span><br><span style="color:#333399;">9.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span><br><span style="color:#333399;">18.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">8</span><br><span style="color:#333399;">24.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">12</span><br><span style="color:#333399;">36.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3</span><br><span style="color:#333399;">9.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">33</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">3</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">9</span><br><span style="color:#333399;">12.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#333399;">9.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">20</span><br><span style="color:#333399;">27.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">29</span><br><span style="color:#333399;">40.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#333399;">9.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">72</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">4</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#333399;">1.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3</span><br><span style="color:#333399;">5.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#333399;">11.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">12</span><br><span style="color:#333399;">20.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">24</span><br><span style="color:#333399;">40.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">12</span><br><span style="color:#333399;">20.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">59</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">4</span><br><span style="color:#333399;">2.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">15</span><br><span style="color:#333399;">8.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">20</span><br><span style="color:#333399;">11.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">41</span><br><span style="color:#333399;">24.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">67</span><br><span style="color:#333399;">39.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">22</span><br><span style="color:#333399;">13&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">169</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="8">χ<sup>2</sup>=41.213 · df=15 · Cramer's V=0.285 · Fisher's p=0.132</td> 
</tr>
 
</tbody></table>
</div>
</div>
</section>
<section id="interpreting-cramers-v" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="interpreting-cramers-v"><span class="header-section-number">5.4.2</span> Interpreting Cramer’s <em>V</em></h3>
<p>Cramer’s <em>V</em> measures the <strong>strength</strong> of association between two categorical variables, independent of sample size. Use the thresholds below to interpret the magnitude. Degrees of freedom (df) here = <span class="math inline">\(\min(r - 1,\, c - 1)\)</span>, where <span class="math inline">\(r\)</span> = number of rows and <span class="math inline">\(c\)</span> = number of columns.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">df</th>
<th style="text-align: center;">Small</th>
<th style="text-align: center;">Medium</th>
<th style="text-align: center;">Large</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.30</td>
<td style="text-align: center;">0.50</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.07</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">0.17</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.04</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">0.22</td>
</tr>
</tbody>
</table>
<div class="note-box question">
<p>How would you interpret a non-significant chi-square result paired with a medium Cramer’s <em>V</em>? What might that combination tell you about sample size?</p>
</div>
</section>
<section id="stacked-bar-chart" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="stacked-bar-chart"><span class="header-section-number">5.4.3</span> Stacked Bar Chart</h3>
<p>A stacked bar chart shows the full distribution of satisfaction levels within each motivation group side by side, making it easy to compare groups visually.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_xtab</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>q1<span class="fl">.3</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  df<span class="sc">$</span>overall_exp,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">margin     =</span> <span class="st">"row"</span>,    <span class="co"># compute percentages within each row (motivation group)</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">bar.pos    =</span> <span class="st">"stack"</span>,  <span class="co"># stack bar segments</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">coord.flip =</span> F      <span class="co"># flip so motivation groups appear on the y axis</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-statistical-analysis_files/figure-html/rq2-stacked-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<div class="note-box note">
<p>Each column is a motivation group. The segments within each bar show what percentage of that group chose each satisfaction level. If the segment pattern looks similar across all rows, the two variables are not strongly related.</p>
</div>
<div class="note-box jamovi">
<p>In Jamovi, Analyses -&gt; Frequencies -&gt; Contigencies Tables -&gt; Independent Samples -&gt; select variables to rows and columns</p>
<p>Under Statistics, check “Chi-square test”, “Fisher’s exact test” and “Phi and Cramer’s V”.</p>
<p>Under Cells, check “Row percentages”. Under Plots, check “Stacked bar plot”.</p>
<p><img src="images/clipboard-2442984020.png" class="img-fluid"></p>
</div>
<div class="note-box note">
<p>A chi-square test of independence examined whether motivation about using technology (Q1.3) was associated with overall online learning experience (Q2.2), using <span class="math inline">\(N = 169\)</span> respondents with complete data on both variables. The test was not significant, <span class="math inline">\(\chi^2(15) = 41.21\)</span>, <span class="math inline">\(p =0.147\)</span>, Cramer’s <span class="math inline">\(V = .285\)</span>. This suggests that motivation and overall experience are not significantly related in this sample, although the medium effect size (Cramer’s <span class="math inline">\(V = .285\)</span>) indicates a moderate association that may warrant further investigation with a larger sample.</p>
</div>
<hr>
</section>
</section>
<section id="rq3-likert-item-analysis-technology-comfort" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="rq3-likert-item-analysis-technology-comfort"><span class="header-section-number">5.5</span> RQ3: Likert Item Analysis — Technology Comfort</h2>
<p><strong>RQ3:</strong> What does the distribution of comfort levels look like across the nine technology tasks in Q1.2?</p>
<p>We use the <code>likert</code> package to compute and visualize the full response profile or the percentage of respondents in each response category — for all nine items at once.</p>
<div class="note-box note">
<p>Item mean collapses the full distribution into one number. Two items can have identical means but very different profiles — for example, one item might be uniformly “somewhat comfortable” while another is split between “mostly uncomfortable” and “mostly comfortable.” The Likert plot reveals the full picture.</p>
</div>
<section id="select-and-label-the-items" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="select-and-label-the-items"><span class="header-section-number">5.5.1</span> Select and Label the Items</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the nine Q1.2 sub-items (columns q1.2a through q1.2i)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># paste0() creates the column names: "q1.2a", "q1.2b", ..., "q1.2i"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>likert_items <span class="ot">&lt;-</span> df[, <span class="fu">paste0</span>(<span class="st">"q1.2"</span>, letters[<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>])]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign descriptive column names (these appear on the plot)</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(likert_items) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Using email"</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Typing / keyboarding"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Accessing the Web"</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sending documents electronically"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Receiving documents electronically"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Downloading documents"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Downloading multimedia materials"</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Listening to audio on the computer"</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Viewing video on the computer"</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(likert_items)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  `Using email` `Typing / keyboarding` `Accessing the Web`
          &lt;dbl&gt;                  &lt;dbl&gt;               &lt;dbl&gt;
1             4                      4                   4
2             4                      4                   4
3             4                      4                   4
4             4                      4                   4
5             4                      4                   4
6             4                      4                   4
# ℹ 6 more variables: `Sending documents electronically` &lt;dbl&gt;,
#   `Receiving documents electronically` &lt;dbl&gt;, `Downloading documents` &lt;dbl&gt;,
#   `Downloading multimedia materials` &lt;dbl&gt;,
#   `Listening to audio on the computer` &lt;dbl&gt;,
#   `Viewing video on the computer` &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="item-level-descriptives-mean-and-sd" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="item-level-descriptives-mean-and-sd"><span class="header-section-number">5.5.2</span> Item-Level Descriptives (Mean and SD)</h3>
<p><code>sapply()</code> applies the same function to every column of a data frame and returns a vector (or matrix) of results. <code>na.rm = TRUE</code> tells the function to ignore missing values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">item    =</span> <span class="fu">names</span>(likert_items),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">valid_n =</span> <span class="fu">sapply</span>(likert_items, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(x))),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean    =</span> <span class="fu">round</span>(<span class="fu">sapply</span>(likert_items, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd      =</span> <span class="fu">round</span>(<span class="fu">sapply</span>(likert_items, sd,   <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                                 item valid_n
Using email                                               Using email     706
Typing / keyboarding                             Typing / keyboarding     706
Accessing the Web                                   Accessing the Web     702
Sending documents electronically     Sending documents electronically     702
Receiving documents electronically Receiving documents electronically     703
Downloading documents                           Downloading documents     704
Downloading multimedia materials     Downloading multimedia materials     683
Listening to audio on the computer Listening to audio on the computer     672
Viewing video on the computer           Viewing video on the computer     656
                                   mean   sd
Using email                        3.81 0.68
Typing / keyboarding               3.75 0.73
Accessing the Web                  3.77 0.70
Sending documents electronically   3.41 0.91
Receiving documents electronically 3.48 0.86
Downloading documents              3.30 0.93
Downloading multimedia materials   2.83 0.99
Listening to audio on the computer 3.13 0.98
Viewing video on the computer      2.93 0.99</code></pre>
</div>
</div>
</section>
<section id="convert-to-labeled-factors-and-fit-the-likert-object" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="convert-to-labeled-factors-and-fit-the-likert-object"><span class="header-section-number">5.5.3</span> Convert to Labeled Factors and Fit the Likert Object</h3>
<p>The <code>likert()</code> function requires <strong>ordered factors</strong> with text labels. <code>lapply()</code> applies the conversion to every column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the four response labels in ascending order</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>likert_labels_4 <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mostly uncomfortable"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Somewhat uncomfortable"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Somewhat comfortable"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mostly comfortable"</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert every column to an ordered factor with these labels</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>likert_items_factor <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  likert_items,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">function</span>(x) <span class="fu">factor</span>(x, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">labels =</span> likert_labels_4, <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the likrt object -- computes the percentage in each category per item</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>likert_fit <span class="ot">&lt;-</span> likert<span class="sc">::</span><span class="fu">likert</span>(likert_items_factor)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the percentage table</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>likert_fit<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                Item Mostly uncomfortable
1                        Using.email             5.099150
2               Typing...keyboarding             5.524079
3                  Accessing.the.Web             4.985755
4   Sending.documents.electronically             7.122507
5 Receiving.documents.electronically             6.258890
6              Downloading.documents             7.244318
7   Downloading.multimedia.materials            11.713031
8 Listening.to.audio.on.the.computer             8.482143
9      Viewing.video.on.the.computer            10.518293
  Somewhat uncomfortable Somewhat comfortable Mostly comfortable
1              0.4249292             2.691218           91.78470
2              0.8498584             6.515581           87.11048
3              0.5698006             6.410256           88.03419
4              7.9772080            21.509972           63.39031
5              5.5476529            22.190612           66.00284
6             10.6534091            27.130682           54.97159
7             23.2796486            35.139092           29.86823
8             16.2202381            28.720238           46.57738
9             20.7317073            33.689024           35.06098</code></pre>
</div>
</div>
</section>
<section id="response-profile-plot" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="response-profile-plot"><span class="header-section-number">5.5.4</span> Response Profile Plot</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(likert_fit,<span class="at">type =</span> <span class="st">"bar"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-statistical-analysis_files/figure-html/rq3-likert-plot-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="note-box note">
<p><strong>How to read this plot:</strong> Each row is one survey item. The colored bar segments show the percentage of respondents choosing each comfort level. Items with a large “Mostly comfortable” segment (dark teal, far right) are tasks respondents feel confident about. Items with large segments on the left (uncomfortable) are where students may need more support or training.</p>
</div>
<div class="note-box jamovi">
<p>In Jamovi, Install vijPlots module</p>
<p>vijPlots -&gt; Likert Plots -&gt; select the nine Q1.2 sub-items (q1.2a through q1.2i) as “Items”</p>
<p>Select the following options to create table and plot</p>
<p><img src="images/clipboard-900807379.png" class="img-fluid"></p>
</div>
<div class="note-box example">
<p><strong>Reporting template (RQ3):</strong></p>
<p>Descriptive analyses of the nine technology-comfort items (Q1.2) showed that mean ratings ranged from <span class="math inline">\(M = 2.83\)</span> (<span class="math inline">\(SD = 0.99\)</span>) for <em>Downloading multimedia materials</em> to <span class="math inline">\(M = 3.81\)</span> (<span class="math inline">\(SD = 0.68\)</span>) for <em>Using email</em> (see Table X). The Likert response profiles (Figure X) indicated that <em>Using email</em> had the highest concentration of “Mostly comfortable” responses (91.8%), whereas <em>Downloading multimedia materials</em> had the largest proportion of uncomfortable responses (35.0% combined across the two uncomfortable categories). These results suggest that students are generally comfortable with basic internet tasks (email, web access, keyboarding) but may need additional support with multimedia-related tasks such as downloading multimedia materials, viewing video, and listening to audio.</p>
</div>
<hr>
</section>
</section>
<section id="rq4-logistic-regression-predicting-willingness-to-register-again" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="rq4-logistic-regression-predicting-willingness-to-register-again"><span class="header-section-number">5.6</span> RQ4: Logistic Regression — Predicting Willingness to Register Again</h2>
<p><strong>RQ4:</strong> Which factors predict whether a respondent would consider registering for another online course if the topic was of interest?</p>
<p><strong>Outcome variable (Q2.9):</strong> Would you consider registering for another online course? (1 = Yes, 0 = No)</p>
<p><strong>Predictor variables:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 45%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Survey Question</th>
<th style="text-align: left;">Scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q2.2</td>
<td style="text-align: left;">Overall satisfaction with online course(s) taken</td>
<td style="text-align: left;">1 (completely dissatisfied) – 6 (completely satisfied)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q2.5</td>
<td style="text-align: left;">Agreement that online courses meet the same quality standards as classroom courses</td>
<td style="text-align: left;">1 (disagree) – 4 (agree)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q1.3</td>
<td style="text-align: left;">Motivation to learn more about using technology tools</td>
<td style="text-align: left;">1 (poor) – 4 (excellent)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q4.3</td>
<td style="text-align: left;">Age range</td>
<td style="text-align: left;">1 (youngest) – 5 (oldest)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q4.4</td>
<td style="text-align: left;">Distance from place of residence to the University</td>
<td style="text-align: left;">1 (closest) – 5 (farthest)</td>
</tr>
</tbody>
</table>
<div class="note-box note">
<p><strong>Why logistic regression?</strong> The outcome variable is binary (Yes / No). Ordinary linear regression is not appropriate for binary outcomes because it can predict values outside the 0–1 range. Logistic regression models the <strong>log-odds</strong> of the outcome and always produces predicted probabilities between 0 and 1.</p>
<p><strong>What is an odds ratio (OR)?</strong> The OR tells you how the <em>odds</em> of “Yes” change for each one-unit increase in a predictor:</p>
<ul>
<li>OR &gt; 1: higher predictor values → higher odds of “Yes”</li>
<li>OR &lt; 1: higher predictor values → lower odds of “Yes”</li>
<li>OR = 1: predictor has no effect on the odds</li>
<li>OR = 2: each one-unit increase <em>doubles</em> the odds of “Yes”</li>
</ul>
</div>
<section id="fit-the-logistic-regression-model" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="fit-the-logistic-regression-model"><span class="header-section-number">5.6.1</span> Fit the Logistic Regression Model</h3>
<p><code>glm()</code> fits a <strong>Generalized Linear Model</strong>. Setting <code>family = binomial(link = "logit")</code> specifies logistic regression. The formula <code>register ~ ...</code> reads: “predict register from the listed predictors.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>logit_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  q2<span class="fl">.9</span> <span class="sc">~</span> q2<span class="fl">.2</span> <span class="sc">+</span> q2<span class="fl">.5</span> <span class="sc">+</span> q1<span class="fl">.3</span> <span class="sc">+</span> q4<span class="fl">.3</span> <span class="sc">+</span> q4<span class="fl">.4</span>,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data   =</span> df,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The summary shows log-odds coefficients (not yet odds ratios)</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = q2.9 ~ q2.2 + q2.5 + q1.3 + q4.3 + q4.4, family = binomial(link = "logit"), 
    data = df)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept) -2.20290    1.33894  -1.645  0.09992 . 
q2.2         0.70736    0.25506   2.773  0.00555 **
q2.5         0.96252    0.36510   2.636  0.00838 **
q1.3        -0.21245    0.33728  -0.630  0.52876   
q4.3         0.16053    0.26103   0.615  0.53856   
q4.4        -0.06161    0.28501  -0.216  0.82886   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 124.402  on 159  degrees of freedom
Residual deviance:  90.087  on 154  degrees of freedom
  (561 observations deleted due to missingness)
AIC: 102.09

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
<section id="model-summary-table-odds-ratios" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="model-summary-table-odds-ratios"><span class="header-section-number">5.6.2</span> Model Summary Table (Odds Ratios)</h3>
<p><code>sjPlot::tab_model()</code> exponentiates the log-odds coefficients to give <strong>odds ratios</strong> and displays them with 95% confidence intervals and p-values — all in one formatted table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_model</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  logit_model,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred.labels =</span> <span class="fu">c</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Intercept"</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Overall satisfaction (Q2.2)"</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Quality standards agreement (Q2.5)"</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Motivation for technology (Q1.3)"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Age range (Q4.3)"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Distance from university (Q4.4)"</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">dv.labels =</span> <span class="st">"Register for another online course (1 = Yes)"</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits    =</span> <span class="dv">3</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Register for another online course (1 = Yes)</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Odds Ratios</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Intercept</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.110</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.007&nbsp;–&nbsp;1.433</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.100</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Overall satisfaction (Q2.2)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.029</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.246&nbsp;–&nbsp;3.421</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.006</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Quality standards agreement (Q2.5)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.618</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.338&nbsp;–&nbsp;5.700</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.008</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Motivation for technology (Q1.3)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.809</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.408&nbsp;–&nbsp;1.552</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.529</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Age range (Q4.3)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.174</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.737&nbsp;–&nbsp;2.120</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.539</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Distance from university (Q4.4)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.940</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.542&nbsp;–&nbsp;1.687</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.829</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">160</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> Tjur</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.231</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="odds-ratio-plot" class="level3" data-number="5.6.3">
<h3 data-number="5.6.3" class="anchored" data-anchor-id="odds-ratio-plot"><span class="header-section-number">5.6.3</span> Odds Ratio Plot</h3>
<p>A forest plot displays each odds ratio as a dot with a horizontal line for its 95% confidence interval. If the line does <strong>not</strong> cross the vertical reference line at OR = 1, the predictor is statistically significant at <span class="math inline">\(\alpha = .05\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">plot_model</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  logit_model,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">type        =</span> <span class="st">"est"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.labels =</span> <span class="fu">c</span>(</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Distance from university (Q4.4)"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Age range (Q4.3)"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Motivation for technology (Q1.3)"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Quality standards agreement (Q2.5)"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Overall satisfaction (Q2.2)"</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">title        =</span> <span class="st">"Odds Ratios: Willingness to Register for Another Online Course"</span>,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">show.values  =</span> <span class="cn">TRUE</span>,</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">value.offset =</span> <span class="fl">0.3</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-statistical-analysis_files/figure-html/logit-or-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="note-box jamovi">
<p>In Jamovi, Analyses -&gt; Regression -&gt; Logistic Regression</p>
<p>Select the following options to create table and plot</p>
<p><img src="images/clipboard-1013060150.png" class="img-fluid"> <img src="images/clipboard-527665642.png" class="img-fluid"></p>
</div>
<div class="note-box note">
<p><strong>How to read this plot:</strong></p>
<ul>
<li>Each <strong>dot</strong> is the estimated odds ratio for that predictor.</li>
<li>The <strong>horizontal line</strong> through the dot is the 95% confidence interval.</li>
<li>The <strong>vertical dashed line</strong> marks OR = 1 (no effect).</li>
<li>If the entire CI is to the <strong>right</strong> of 1, the predictor significantly increases the odds of “Yes.”</li>
<li>If the entire CI is to the <strong>left</strong> of 1, the predictor significantly decreases the odds.</li>
<li>If the CI <strong>crosses</strong> 1, the predictor is not statistically significant at <span class="math inline">\(\alpha = .05\)</span>.</li>
</ul>
</div>
<div class="note-box example">
<p><strong>Reporting template (RQ4):</strong></p>
<p>A binary logistic regression was conducted to identify predictors of willingness to register for another online course (<span class="math inline">\(N = 160\)</span>). Two predictors were statistically significant. Overall satisfaction with online coursework was a significant positive predictor (OR = 2.03, 95% CI [1.25, 3.42], <span class="math inline">\(p = .006\)</span>), indicating that each one-unit increase in satisfaction was associated with approximately twice the odds of willingness to register again. Agreement that online courses meet the same quality standards as classroom courses was also a significant positive predictor (OR = 2.62, 95% CI [1.34, 5.70], <span class="math inline">\(p = .008\)</span>). Motivation for technology use (OR = 0.81, 95% CI [0.41, 1.55], <span class="math inline">\(p = .529\)</span>), age range (OR = 1.17, 95% CI [0.74, 2.12], <span class="math inline">\(p = .539\)</span>), and distance from the university (OR = 0.94, 95% CI [0.54, 1.69], <span class="math inline">\(p = .829\)</span>) were not statistically significant predictors.</p>
</div>
<hr>
</section>
</section>
<section id="summary-what-to-report" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="summary-what-to-report"><span class="header-section-number">5.7</span> Summary: What to Report</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">RQ</th>
<th style="text-align: left;">Method</th>
<th style="text-align: left;">Key statistics to report</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">RQ1</td>
<td style="text-align: left;">Frequency table + bar chart</td>
<td style="text-align: left;"><em>N</em>, % per category, combined satisfied/dissatisfied %</td>
</tr>
<tr class="even">
<td style="text-align: left;">RQ2</td>
<td style="text-align: left;">Chi-square + Cramer’s <em>V</em></td>
<td style="text-align: left;"><span class="math inline">\(\chi^2\)</span>, df, <em>p</em>, Cramer’s <em>V</em>, effect size interpretation</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RQ3</td>
<td style="text-align: left;">Likert response profile</td>
<td style="text-align: left;">Mean and SD per item; % in each response category</td>
</tr>
<tr class="even">
<td style="text-align: left;">RQ4</td>
<td style="text-align: left;">Binary logistic regression</td>
<td style="text-align: left;">OR with 95% CI and <em>p</em> per predictor</td>
</tr>
</tbody>
</table>
</section>
<section id="exercise" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="exercise"><span class="header-section-number">5.8</span> Exercise</h2>
<p>Using the same data, answer the following research questions:</p>
<ul>
<li>Describe where the primary computer is located for the participants in the sample (Q1.1)?</li>
<li>What’s the relationship between whether they will recommend online courses to others (Q2.9) and their overall satisfaction with online courses (Q2.2)? Create a contingency table, chi-square test, and Cramer’s <em>V</em> to answer this question. Then write a brief report summarizing the results.</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-psychometric-analysis.html" class="pagination-link" aria-label="Psychometric Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Psychometric Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-multiple-imputation.html" class="pagination-link" aria-label="Multiple Imputation">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Imputation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb26" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Statistical Analysis"</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>This handout uses the <span class="co">[</span><span class="ot">2001 Learning and Technology Survey</span><span class="co">](http://edmeasurement.net/5244/2001-survey.html)</span> for illustration. The survey collected information on students' technology comfort, online learning experiences, and demographics.</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>Data source:</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Survey instrument: http://edmeasurement.net/5244/2001-survey.html</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>SPSS data: https://raw.githubusercontent.com/Wenchao-Ma/Data/main/EDM2001/2001-data.sav</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="fu">## Research Questions</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>This handout addresses four research questions that progress from simple description to multivariate prediction:</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>| <span class="sc">\#</span> | Research Question | Analysis Method |</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>|:------------------|:--------------------------|:-------------------------|</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>| RQ1 | Overall, to what extent are students dissatisfied or satisfied with the online course(s) they have taken? | Frequency table + bar chart |</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>| RQ2 | Is motivation about using technology tools related to overall online learning experience? | Chi-square test + Cramer's *V* |</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>| RQ3 | What does the distribution of technology comfort look like across the nine Q1.2 items? | Likert response profile |</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>| RQ4 | Which factors predict whether students would consider registering for another online course? | Binary logistic regression |</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a><span class="in">```{r install-packages, eval=FALSE}</span></span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="in"># Run this block ONCE to install all required packages.</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a><span class="in"># After installation you never need to run it again.</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a><span class="in">#install.packages(c("ggplot2", "likert", "scales", "sjPlot"))</span></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a><span class="in">```{r load-packages, message=FALSE}</span></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a><span class="in"># Load packages at the start of every R session.</span></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a><span class="in">library(ggplot2)   # creating plots</span></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a><span class="in">library(likert)    # Likert response profile plots</span></span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a><span class="in">library(scales)    # formatting axis labels</span></span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a><span class="in">library(haven)</span></span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a><span class="in">library(sjPlot)    # contingency tables and regression output</span></span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## Import the Data</span></span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-42"><a href="#cb26-42" aria-hidden="true" tabindex="-1"></a><span class="in">`read_sav()`</span> reads an SPSS data file — either from your computer or directly from a URL — into a data frame. Recall that a data frame is R's version of a spreadsheet: rows are respondents, columns are variables.</span>
<span id="cb26-43"><a href="#cb26-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-44"><a href="#cb26-44" aria-hidden="true" tabindex="-1"></a><span class="in">```{r import-data}</span></span>
<span id="cb26-45"><a href="#cb26-45" aria-hidden="true" tabindex="-1"></a><span class="in"># Read the SPSS file directly from the web into a data frame named df</span></span>
<span id="cb26-46"><a href="#cb26-46" aria-hidden="true" tabindex="-1"></a><span class="in">df &lt;- haven::read_sav(</span></span>
<span id="cb26-47"><a href="#cb26-47" aria-hidden="true" tabindex="-1"></a><span class="in">  "https://raw.githubusercontent.com/Wenchao-Ma/Data/main/EDM2001/2001-data.sav",user_na = FALSE,</span></span>
<span id="cb26-48"><a href="#cb26-48" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-49"><a href="#cb26-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-50"><a href="#cb26-50" aria-hidden="true" tabindex="-1"></a><span class="in"># Check the dimensions: rows = respondents, columns = variables</span></span>
<span id="cb26-51"><a href="#cb26-51" aria-hidden="true" tabindex="-1"></a><span class="in">dim(df)</span></span>
<span id="cb26-52"><a href="#cb26-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-53"><a href="#cb26-53" aria-hidden="true" tabindex="-1"></a><span class="in"># Preview the first six rows</span></span>
<span id="cb26-54"><a href="#cb26-54" aria-hidden="true" tabindex="-1"></a><span class="in">head(df)</span></span>
<span id="cb26-55"><a href="#cb26-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-56"><a href="#cb26-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-57"><a href="#cb26-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## RQ1: Overall Satisfaction With Online Course(s)</span></span>
<span id="cb26-58"><a href="#cb26-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-59"><a href="#cb26-59" aria-hidden="true" tabindex="-1"></a>**Question:** Overall, to what extent are students dissatisfied or satisfied with the online course(s) they have taken? (Q2.2, six-point scale)</span>
<span id="cb26-60"><a href="#cb26-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-61"><a href="#cb26-61" aria-hidden="true" tabindex="-1"></a>Q2.2 is a single categorical variable, so we describe its distribution with a frequency table (counts and percentages) and a bar chart.</span>
<span id="cb26-62"><a href="#cb26-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-63"><a href="#cb26-63" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq1-data}</span></span>
<span id="cb26-64"><a href="#cb26-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-65"><a href="#cb26-65" aria-hidden="true" tabindex="-1"></a><span class="in"># ------------------------------------------------------------------</span></span>
<span id="cb26-66"><a href="#cb26-66" aria-hidden="true" tabindex="-1"></a><span class="in"># Q2.2: Overall, to what extent are you dissatisfied or satisfied</span></span>
<span id="cb26-67"><a href="#cb26-67" aria-hidden="true" tabindex="-1"></a><span class="in">#        with the online course(s) you have taken?</span></span>
<span id="cb26-68"><a href="#cb26-68" aria-hidden="true" tabindex="-1"></a><span class="in">#        1 = Completely dissatisfied  ...  6 = Completely satisfied</span></span>
<span id="cb26-69"><a href="#cb26-69" aria-hidden="true" tabindex="-1"></a><span class="in"># ------------------------------------------------------------------</span></span>
<span id="cb26-70"><a href="#cb26-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-71"><a href="#cb26-71" aria-hidden="true" tabindex="-1"></a><span class="in">df$overall_exp_num &lt;- df$q2.2   </span></span>
<span id="cb26-72"><a href="#cb26-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-73"><a href="#cb26-73" aria-hidden="true" tabindex="-1"></a><span class="in">df$overall_exp &lt;- factor(</span></span>
<span id="cb26-74"><a href="#cb26-74" aria-hidden="true" tabindex="-1"></a><span class="in">  df$q2.2,</span></span>
<span id="cb26-75"><a href="#cb26-75" aria-hidden="true" tabindex="-1"></a><span class="in">  levels  = 1:6,</span></span>
<span id="cb26-76"><a href="#cb26-76" aria-hidden="true" tabindex="-1"></a><span class="in">  labels  = c(</span></span>
<span id="cb26-77"><a href="#cb26-77" aria-hidden="true" tabindex="-1"></a><span class="in">    "Completely dissatisfied",</span></span>
<span id="cb26-78"><a href="#cb26-78" aria-hidden="true" tabindex="-1"></a><span class="in">    "Mostly dissatisfied",</span></span>
<span id="cb26-79"><a href="#cb26-79" aria-hidden="true" tabindex="-1"></a><span class="in">    "Somewhat dissatisfied",</span></span>
<span id="cb26-80"><a href="#cb26-80" aria-hidden="true" tabindex="-1"></a><span class="in">    "Somewhat satisfied",</span></span>
<span id="cb26-81"><a href="#cb26-81" aria-hidden="true" tabindex="-1"></a><span class="in">    "Mostly satisfied",</span></span>
<span id="cb26-82"><a href="#cb26-82" aria-hidden="true" tabindex="-1"></a><span class="in">    "Completely satisfied"</span></span>
<span id="cb26-83"><a href="#cb26-83" aria-hidden="true" tabindex="-1"></a><span class="in">  ),</span></span>
<span id="cb26-84"><a href="#cb26-84" aria-hidden="true" tabindex="-1"></a><span class="in">  ordered = TRUE   # ordered = TRUE tells R this is an ordinal scale</span></span>
<span id="cb26-85"><a href="#cb26-85" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-86"><a href="#cb26-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-87"><a href="#cb26-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-88"><a href="#cb26-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-89"><a href="#cb26-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-90"><a href="#cb26-90" aria-hidden="true" tabindex="-1"></a><span class="fu">### Frequency Table</span></span>
<span id="cb26-91"><a href="#cb26-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-92"><a href="#cb26-92" aria-hidden="true" tabindex="-1"></a><span class="in">`table()`</span> counts how many respondents chose each category. <span class="in">`prop.table()`</span> converts those counts into proportions, which we multiply by 100 to get percentages.</span>
<span id="cb26-93"><a href="#cb26-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-94"><a href="#cb26-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq1-proportions}</span></span>
<span id="cb26-95"><a href="#cb26-95" aria-hidden="true" tabindex="-1"></a><span class="in">rq1_counts &lt;- table(df$overall_exp)       # raw counts</span></span>
<span id="cb26-96"><a href="#cb26-96" aria-hidden="true" tabindex="-1"></a><span class="in">rq1_props  &lt;- prop.table(rq1_counts)       # proportions (each / total)</span></span>
<span id="cb26-97"><a href="#cb26-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-98"><a href="#cb26-98" aria-hidden="true" tabindex="-1"></a><span class="in"># Combine into a readable data frame</span></span>
<span id="cb26-99"><a href="#cb26-99" aria-hidden="true" tabindex="-1"></a><span class="in">data.frame(</span></span>
<span id="cb26-100"><a href="#cb26-100" aria-hidden="true" tabindex="-1"></a><span class="in">  response   = names(rq1_counts),</span></span>
<span id="cb26-101"><a href="#cb26-101" aria-hidden="true" tabindex="-1"></a><span class="in">  count      = as.integer(rq1_counts),</span></span>
<span id="cb26-102"><a href="#cb26-102" aria-hidden="true" tabindex="-1"></a><span class="in">  proportion = round(as.numeric(rq1_props), 3),</span></span>
<span id="cb26-103"><a href="#cb26-103" aria-hidden="true" tabindex="-1"></a><span class="in">  percent    = round(100 * as.numeric(rq1_props), 1)</span></span>
<span id="cb26-104"><a href="#cb26-104" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-105"><a href="#cb26-105" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-106"><a href="#cb26-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-107"><a href="#cb26-107" aria-hidden="true" tabindex="-1"></a><span class="fu">### Collapsed Summary</span></span>
<span id="cb26-108"><a href="#cb26-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-109"><a href="#cb26-109" aria-hidden="true" tabindex="-1"></a>To simplify reporting we combine the three satisfied categories and the three dissatisfied categories into two groups.</span>
<span id="cb26-110"><a href="#cb26-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-111"><a href="#cb26-111" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq1-collapsed}</span></span>
<span id="cb26-112"><a href="#cb26-112" aria-hidden="true" tabindex="-1"></a><span class="in"># Proportion who chose "Somewhat satisfied" or higher (codes 4, 5, 6)</span></span>
<span id="cb26-113"><a href="#cb26-113" aria-hidden="true" tabindex="-1"></a><span class="in">prop_satisfied    &lt;- mean(df$overall_exp_num &gt;= 4,na.rm = TRUE)</span></span>
<span id="cb26-114"><a href="#cb26-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-115"><a href="#cb26-115" aria-hidden="true" tabindex="-1"></a><span class="in"># Proportion who chose "Somewhat dissatisfied" or lower (codes 1, 2, 3)</span></span>
<span id="cb26-116"><a href="#cb26-116" aria-hidden="true" tabindex="-1"></a><span class="in">prop_dissatisfied &lt;- mean(df$overall_exp_num &lt;= 3,na.rm = TRUE)</span></span>
<span id="cb26-117"><a href="#cb26-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-118"><a href="#cb26-118" aria-hidden="true" tabindex="-1"></a><span class="in">data.frame(</span></span>
<span id="cb26-119"><a href="#cb26-119" aria-hidden="true" tabindex="-1"></a><span class="in">  group      = c("Somewhat or more satisfied", "Somewhat or more dissatisfied"),</span></span>
<span id="cb26-120"><a href="#cb26-120" aria-hidden="true" tabindex="-1"></a><span class="in">  proportion = round(c(prop_satisfied, prop_dissatisfied), 3)</span></span>
<span id="cb26-121"><a href="#cb26-121" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-122"><a href="#cb26-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-123"><a href="#cb26-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-124"><a href="#cb26-124" aria-hidden="true" tabindex="-1"></a><span class="fu">### Bar Chart</span></span>
<span id="cb26-125"><a href="#cb26-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-126"><a href="#cb26-126" aria-hidden="true" tabindex="-1"></a><span class="in">`ggplot2`</span> builds plots layer by layer. <span class="in">`aes()`</span> maps variables to visual properties (x axis, y axis). <span class="in">`geom_col()`</span> draws bars. <span class="in">`labs()`</span> sets titles and axis labels.</span>
<span id="cb26-127"><a href="#cb26-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-128"><a href="#cb26-128" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq1-bar, fig.width=9, fig.height=4}</span></span>
<span id="cb26-129"><a href="#cb26-129" aria-hidden="true" tabindex="-1"></a><span class="in"># Convert the frequency table to a data frame for ggplot</span></span>
<span id="cb26-130"><a href="#cb26-130" aria-hidden="true" tabindex="-1"></a><span class="in">rq1_plot_df &lt;- as.data.frame(rq1_counts)</span></span>
<span id="cb26-131"><a href="#cb26-131" aria-hidden="true" tabindex="-1"></a><span class="in">names(rq1_plot_df) &lt;- c("overall_exp", "count")</span></span>
<span id="cb26-132"><a href="#cb26-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-133"><a href="#cb26-133" aria-hidden="true" tabindex="-1"></a><span class="in">ggplot(rq1_plot_df, aes(x = overall_exp, y = count)) +</span></span>
<span id="cb26-134"><a href="#cb26-134" aria-hidden="true" tabindex="-1"></a><span class="in">  geom_col(fill = "steelblue") +</span></span>
<span id="cb26-135"><a href="#cb26-135" aria-hidden="true" tabindex="-1"></a><span class="in">  labs(</span></span>
<span id="cb26-136"><a href="#cb26-136" aria-hidden="true" tabindex="-1"></a><span class="in">    title = "Overall Satisfaction With Online Course(s) (Q2.2)",</span></span>
<span id="cb26-137"><a href="#cb26-137" aria-hidden="true" tabindex="-1"></a><span class="in">    x     = "Response category",</span></span>
<span id="cb26-138"><a href="#cb26-138" aria-hidden="true" tabindex="-1"></a><span class="in">    y     = "Number of respondents"</span></span>
<span id="cb26-139"><a href="#cb26-139" aria-hidden="true" tabindex="-1"></a><span class="in">  ) +</span></span>
<span id="cb26-140"><a href="#cb26-140" aria-hidden="true" tabindex="-1"></a><span class="in">  theme_bw() +</span></span>
<span id="cb26-141"><a href="#cb26-141" aria-hidden="true" tabindex="-1"></a><span class="in">  # Rotate x-axis labels so they don't overlap</span></span>
<span id="cb26-142"><a href="#cb26-142" aria-hidden="true" tabindex="-1"></a><span class="in">  theme(axis.text.x = element_text(angle = 20, hjust = 1))</span></span>
<span id="cb26-143"><a href="#cb26-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-144"><a href="#cb26-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-145"><a href="#cb26-145" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-146"><a href="#cb26-146" aria-hidden="true" tabindex="-1"></a>**Reporting template (RQ1):**</span>
<span id="cb26-147"><a href="#cb26-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-148"><a href="#cb26-148" aria-hidden="true" tabindex="-1"></a>Among respondents with non-missing ratings on overall online-course experience ($N = 170$), the majority reported positive experiences: 24.1% somewhat satisfied, 40.0% mostly satisfied, and 12.9% completely satisfied (77.1% combined). A smaller proportion reported dissatisfaction: 11.8% somewhat dissatisfied, 8.8% mostly dissatisfied, and 2.4% completely dissatisfied (22.9% combined; see Figure X).</span>
<span id="cb26-149"><a href="#cb26-149" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-150"><a href="#cb26-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-151"><a href="#cb26-151" aria-hidden="true" tabindex="-1"></a>::: {.note-box .exercise}</span>
<span id="cb26-152"><a href="#cb26-152" aria-hidden="true" tabindex="-1"></a>Check the total number of respondents in 5.5.2? Is it the same as the number of responses in the sample? If not, why might that be?</span>
<span id="cb26-153"><a href="#cb26-153" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-154"><a href="#cb26-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-155"><a href="#cb26-155" aria-hidden="true" tabindex="-1"></a>::: {.note-box .jamovi}</span>
<span id="cb26-156"><a href="#cb26-156" aria-hidden="true" tabindex="-1"></a>In Jamovi, Analyses -<span class="sc">\&gt;</span> Exploration -<span class="sc">\&gt;</span> Descriptives -<span class="sc">\&gt;</span> select Q2.2 -<span class="sc">\&gt;</span> check "Frequency tables" and "Bar plot"</span>
<span id="cb26-157"><a href="#cb26-157" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-158"><a href="#cb26-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-159"><a href="#cb26-159" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb26-160"><a href="#cb26-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-161"><a href="#cb26-161" aria-hidden="true" tabindex="-1"></a><span class="fu">## RQ2: Motivation and Overall Online Learning Experience</span></span>
<span id="cb26-162"><a href="#cb26-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-163"><a href="#cb26-163" aria-hidden="true" tabindex="-1"></a>**RQ2:** Is motivation about using technology tools (Q1.3) associated with overall online learning experience (Q2.2)?</span>
<span id="cb26-164"><a href="#cb26-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-165"><a href="#cb26-165" aria-hidden="true" tabindex="-1"></a>Both variables are categorical, so we use a chi-square test of independence to test whether the two variables are related, and Cramer's V to quantify the strength of that association.</span>
<span id="cb26-166"><a href="#cb26-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-167"><a href="#cb26-167" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-168"><a href="#cb26-168" aria-hidden="true" tabindex="-1"></a>The chi-square test checks whether the distribution of satisfaction ratings looks the same across all motivation groups. A significant result ($p &lt; .05$) means the groups differ more than we would expect by chance. A non-significant result means any observed differences are within the range of random variation.</span>
<span id="cb26-169"><a href="#cb26-169" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-170"><a href="#cb26-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-171"><a href="#cb26-171" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cross-Tabulation and Chi-Square Test</span></span>
<span id="cb26-172"><a href="#cb26-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-173"><a href="#cb26-173" aria-hidden="true" tabindex="-1"></a><span class="in">`sjPlot::tab_xtab()`</span> produces a contingency table, chi-square test, and Cramer's *V* in one step. <span class="in">`show.row.prc = TRUE`</span> displays row percentages, making it easier to compare distributions across motivation groups.</span>
<span id="cb26-174"><a href="#cb26-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-175"><a href="#cb26-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq2-crosstab}</span></span>
<span id="cb26-176"><a href="#cb26-176" aria-hidden="true" tabindex="-1"></a><span class="in">sjPlot::tab_xtab(</span></span>
<span id="cb26-177"><a href="#cb26-177" aria-hidden="true" tabindex="-1"></a><span class="in">  var.row      = df$q1.3,</span></span>
<span id="cb26-178"><a href="#cb26-178" aria-hidden="true" tabindex="-1"></a><span class="in">  var.col      = df$overall_exp,</span></span>
<span id="cb26-179"><a href="#cb26-179" aria-hidden="true" tabindex="-1"></a><span class="in">  show.row.prc = TRUE</span></span>
<span id="cb26-180"><a href="#cb26-180" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-181"><a href="#cb26-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-182"><a href="#cb26-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-183"><a href="#cb26-183" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpreting Cramer's *V*</span></span>
<span id="cb26-184"><a href="#cb26-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-185"><a href="#cb26-185" aria-hidden="true" tabindex="-1"></a>Cramer's *V* measures the **strength** of association between two categorical variables, independent of sample size. Use the thresholds below to interpret the magnitude. Degrees of freedom (df) here = $\min(r - 1,\, c - 1)$, where $r$ = number of rows and $c$ = number of columns.</span>
<span id="cb26-186"><a href="#cb26-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-187"><a href="#cb26-187" aria-hidden="true" tabindex="-1"></a>| df  | Small | Medium | Large |</span>
<span id="cb26-188"><a href="#cb26-188" aria-hidden="true" tabindex="-1"></a>|:---:|:-----:|:------:|:-----:|</span>
<span id="cb26-189"><a href="#cb26-189" aria-hidden="true" tabindex="-1"></a>|  1  | 0.10  |  0.30  | 0.50  |</span>
<span id="cb26-190"><a href="#cb26-190" aria-hidden="true" tabindex="-1"></a>|  2  | 0.07  |  0.21  | 0.35  |</span>
<span id="cb26-191"><a href="#cb26-191" aria-hidden="true" tabindex="-1"></a>|  3  | 0.06  |  0.17  | 0.29  |</span>
<span id="cb26-192"><a href="#cb26-192" aria-hidden="true" tabindex="-1"></a>|  4  | 0.05  |  0.15  | 0.25  |</span>
<span id="cb26-193"><a href="#cb26-193" aria-hidden="true" tabindex="-1"></a>|  5  | 0.04  |  0.13  | 0.22  |</span>
<span id="cb26-194"><a href="#cb26-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-195"><a href="#cb26-195" aria-hidden="true" tabindex="-1"></a>::: {.note-box .question}</span>
<span id="cb26-196"><a href="#cb26-196" aria-hidden="true" tabindex="-1"></a>How would you interpret a non-significant chi-square result paired with a medium Cramer's *V*? What might that combination tell you about sample size?</span>
<span id="cb26-197"><a href="#cb26-197" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-198"><a href="#cb26-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-199"><a href="#cb26-199" aria-hidden="true" tabindex="-1"></a><span class="fu">### Stacked Bar Chart</span></span>
<span id="cb26-200"><a href="#cb26-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-201"><a href="#cb26-201" aria-hidden="true" tabindex="-1"></a>A stacked bar chart shows the full distribution of satisfaction levels within each motivation group side by side, making it easy to compare groups visually.</span>
<span id="cb26-202"><a href="#cb26-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-203"><a href="#cb26-203" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq2-stacked, fig.width=9, fig.height=10}</span></span>
<span id="cb26-204"><a href="#cb26-204" aria-hidden="true" tabindex="-1"></a><span class="in">sjPlot::plot_xtab(</span></span>
<span id="cb26-205"><a href="#cb26-205" aria-hidden="true" tabindex="-1"></a><span class="in">  df$q1.3,</span></span>
<span id="cb26-206"><a href="#cb26-206" aria-hidden="true" tabindex="-1"></a><span class="in">  df$overall_exp,</span></span>
<span id="cb26-207"><a href="#cb26-207" aria-hidden="true" tabindex="-1"></a><span class="in">  margin     = "row",    # compute percentages within each row (motivation group)</span></span>
<span id="cb26-208"><a href="#cb26-208" aria-hidden="true" tabindex="-1"></a><span class="in">  bar.pos    = "stack",  # stack bar segments</span></span>
<span id="cb26-209"><a href="#cb26-209" aria-hidden="true" tabindex="-1"></a><span class="in">  coord.flip = F      # flip so motivation groups appear on the y axis</span></span>
<span id="cb26-210"><a href="#cb26-210" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-211"><a href="#cb26-211" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-212"><a href="#cb26-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-213"><a href="#cb26-213" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-214"><a href="#cb26-214" aria-hidden="true" tabindex="-1"></a>Each column is a motivation group. The segments within each bar show what percentage of that group chose each satisfaction level. If the segment pattern looks similar across all rows, the two variables are not strongly related.</span>
<span id="cb26-215"><a href="#cb26-215" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-216"><a href="#cb26-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-217"><a href="#cb26-217" aria-hidden="true" tabindex="-1"></a>::: {.note-box .jamovi}</span>
<span id="cb26-218"><a href="#cb26-218" aria-hidden="true" tabindex="-1"></a>In Jamovi, Analyses -<span class="sc">\&gt;</span> Frequencies -<span class="sc">\&gt;</span> Contigencies Tables -<span class="sc">\&gt;</span> Independent Samples -<span class="sc">\&gt;</span> select variables to rows and columns</span>
<span id="cb26-219"><a href="#cb26-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-220"><a href="#cb26-220" aria-hidden="true" tabindex="-1"></a>Under Statistics, check "Chi-square test", "Fisher's exact test" and "Phi and Cramer's V".</span>
<span id="cb26-221"><a href="#cb26-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-222"><a href="#cb26-222" aria-hidden="true" tabindex="-1"></a>Under Cells, check "Row percentages". Under Plots, check "Stacked bar plot".</span>
<span id="cb26-223"><a href="#cb26-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-224"><a href="#cb26-224" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/clipboard-2442984020.png)</span></span>
<span id="cb26-225"><a href="#cb26-225" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-226"><a href="#cb26-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-227"><a href="#cb26-227" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-228"><a href="#cb26-228" aria-hidden="true" tabindex="-1"></a>A chi-square test of independence examined whether motivation about using technology (Q1.3) was associated with overall online learning experience (Q2.2), using $N = 169$ respondents with complete data on both variables. The test was not significant, $\chi^2(15) = 41.21$, $p =0.147$, Cramer's $V = .285$. This suggests that motivation and overall experience are not significantly related in this sample, although the medium effect size (Cramer's $V = .285$) indicates a moderate association that may warrant further investigation with a larger sample.</span>
<span id="cb26-229"><a href="#cb26-229" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-230"><a href="#cb26-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-231"><a href="#cb26-231" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb26-232"><a href="#cb26-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-233"><a href="#cb26-233" aria-hidden="true" tabindex="-1"></a><span class="fu">## RQ3: Likert Item Analysis — Technology Comfort</span></span>
<span id="cb26-234"><a href="#cb26-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-235"><a href="#cb26-235" aria-hidden="true" tabindex="-1"></a>**RQ3:** What does the distribution of comfort levels look like across the nine technology tasks in Q1.2?</span>
<span id="cb26-236"><a href="#cb26-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-237"><a href="#cb26-237" aria-hidden="true" tabindex="-1"></a>We use the <span class="in">`likert`</span> package to compute and visualize the full response profile or the percentage of respondents in each response category — for all nine items at once.</span>
<span id="cb26-238"><a href="#cb26-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-239"><a href="#cb26-239" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-240"><a href="#cb26-240" aria-hidden="true" tabindex="-1"></a>Item mean collapses the full distribution into one number. Two items can have identical means but very different profiles — for example, one item might be uniformly "somewhat comfortable" while another is split between "mostly uncomfortable" and "mostly comfortable." The Likert plot reveals the full picture.</span>
<span id="cb26-241"><a href="#cb26-241" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-242"><a href="#cb26-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-243"><a href="#cb26-243" aria-hidden="true" tabindex="-1"></a><span class="fu">### Select and Label the Items</span></span>
<span id="cb26-244"><a href="#cb26-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-245"><a href="#cb26-245" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq3-select-items}</span></span>
<span id="cb26-246"><a href="#cb26-246" aria-hidden="true" tabindex="-1"></a><span class="in"># Select the nine Q1.2 sub-items (columns q1.2a through q1.2i)</span></span>
<span id="cb26-247"><a href="#cb26-247" aria-hidden="true" tabindex="-1"></a><span class="in"># paste0() creates the column names: "q1.2a", "q1.2b", ..., "q1.2i"</span></span>
<span id="cb26-248"><a href="#cb26-248" aria-hidden="true" tabindex="-1"></a><span class="in">likert_items &lt;- df[, paste0("q1.2", letters[1:9])]</span></span>
<span id="cb26-249"><a href="#cb26-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-250"><a href="#cb26-250" aria-hidden="true" tabindex="-1"></a><span class="in"># Assign descriptive column names (these appear on the plot)</span></span>
<span id="cb26-251"><a href="#cb26-251" aria-hidden="true" tabindex="-1"></a><span class="in">names(likert_items) &lt;- c(</span></span>
<span id="cb26-252"><a href="#cb26-252" aria-hidden="true" tabindex="-1"></a><span class="in">  "Using email",</span></span>
<span id="cb26-253"><a href="#cb26-253" aria-hidden="true" tabindex="-1"></a><span class="in">  "Typing / keyboarding",</span></span>
<span id="cb26-254"><a href="#cb26-254" aria-hidden="true" tabindex="-1"></a><span class="in">  "Accessing the Web",</span></span>
<span id="cb26-255"><a href="#cb26-255" aria-hidden="true" tabindex="-1"></a><span class="in">  "Sending documents electronically",</span></span>
<span id="cb26-256"><a href="#cb26-256" aria-hidden="true" tabindex="-1"></a><span class="in">  "Receiving documents electronically",</span></span>
<span id="cb26-257"><a href="#cb26-257" aria-hidden="true" tabindex="-1"></a><span class="in">  "Downloading documents",</span></span>
<span id="cb26-258"><a href="#cb26-258" aria-hidden="true" tabindex="-1"></a><span class="in">  "Downloading multimedia materials",</span></span>
<span id="cb26-259"><a href="#cb26-259" aria-hidden="true" tabindex="-1"></a><span class="in">  "Listening to audio on the computer",</span></span>
<span id="cb26-260"><a href="#cb26-260" aria-hidden="true" tabindex="-1"></a><span class="in">  "Viewing video on the computer"</span></span>
<span id="cb26-261"><a href="#cb26-261" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-262"><a href="#cb26-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-263"><a href="#cb26-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-264"><a href="#cb26-264" aria-hidden="true" tabindex="-1"></a><span class="in">head(likert_items)</span></span>
<span id="cb26-265"><a href="#cb26-265" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-266"><a href="#cb26-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-267"><a href="#cb26-267" aria-hidden="true" tabindex="-1"></a><span class="fu">### Item-Level Descriptives (Mean and SD)</span></span>
<span id="cb26-268"><a href="#cb26-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-269"><a href="#cb26-269" aria-hidden="true" tabindex="-1"></a><span class="in">`sapply()`</span> applies the same function to every column of a data frame and returns a vector (or matrix) of results. <span class="in">`na.rm = TRUE`</span> tells the function to ignore missing values.</span>
<span id="cb26-270"><a href="#cb26-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-271"><a href="#cb26-271" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq3-item-summary}</span></span>
<span id="cb26-272"><a href="#cb26-272" aria-hidden="true" tabindex="-1"></a><span class="in">data.frame(</span></span>
<span id="cb26-273"><a href="#cb26-273" aria-hidden="true" tabindex="-1"></a><span class="in">  item    = names(likert_items),</span></span>
<span id="cb26-274"><a href="#cb26-274" aria-hidden="true" tabindex="-1"></a><span class="in">  valid_n = sapply(likert_items, function(x) sum(!is.na(x))),</span></span>
<span id="cb26-275"><a href="#cb26-275" aria-hidden="true" tabindex="-1"></a><span class="in">  mean    = round(sapply(likert_items, mean, na.rm = TRUE), 2),</span></span>
<span id="cb26-276"><a href="#cb26-276" aria-hidden="true" tabindex="-1"></a><span class="in">  sd      = round(sapply(likert_items, sd,   na.rm = TRUE), 2)</span></span>
<span id="cb26-277"><a href="#cb26-277" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-278"><a href="#cb26-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-279"><a href="#cb26-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-280"><a href="#cb26-280" aria-hidden="true" tabindex="-1"></a><span class="fu">### Convert to Labeled Factors and Fit the Likert Object</span></span>
<span id="cb26-281"><a href="#cb26-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-282"><a href="#cb26-282" aria-hidden="true" tabindex="-1"></a>The <span class="in">`likert()`</span> function requires **ordered factors** with text labels. <span class="in">`lapply()`</span> applies the conversion to every column.</span>
<span id="cb26-283"><a href="#cb26-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-284"><a href="#cb26-284" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq3-likert-fit}</span></span>
<span id="cb26-285"><a href="#cb26-285" aria-hidden="true" tabindex="-1"></a><span class="in"># Define the four response labels in ascending order</span></span>
<span id="cb26-286"><a href="#cb26-286" aria-hidden="true" tabindex="-1"></a><span class="in">likert_labels_4 &lt;- c(</span></span>
<span id="cb26-287"><a href="#cb26-287" aria-hidden="true" tabindex="-1"></a><span class="in">  "Mostly uncomfortable",</span></span>
<span id="cb26-288"><a href="#cb26-288" aria-hidden="true" tabindex="-1"></a><span class="in">  "Somewhat uncomfortable",</span></span>
<span id="cb26-289"><a href="#cb26-289" aria-hidden="true" tabindex="-1"></a><span class="in">  "Somewhat comfortable",</span></span>
<span id="cb26-290"><a href="#cb26-290" aria-hidden="true" tabindex="-1"></a><span class="in">  "Mostly comfortable"</span></span>
<span id="cb26-291"><a href="#cb26-291" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-292"><a href="#cb26-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-293"><a href="#cb26-293" aria-hidden="true" tabindex="-1"></a><span class="in"># Convert every column to an ordered factor with these labels</span></span>
<span id="cb26-294"><a href="#cb26-294" aria-hidden="true" tabindex="-1"></a><span class="in">likert_items_factor &lt;- as.data.frame(lapply(</span></span>
<span id="cb26-295"><a href="#cb26-295" aria-hidden="true" tabindex="-1"></a><span class="in">  likert_items,</span></span>
<span id="cb26-296"><a href="#cb26-296" aria-hidden="true" tabindex="-1"></a><span class="in">  function(x) factor(x, levels = 1:4, labels = likert_labels_4, ordered = TRUE)</span></span>
<span id="cb26-297"><a href="#cb26-297" aria-hidden="true" tabindex="-1"></a><span class="in">))</span></span>
<span id="cb26-298"><a href="#cb26-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-299"><a href="#cb26-299" aria-hidden="true" tabindex="-1"></a><span class="in"># Fit the likrt object -- computes the percentage in each category per item</span></span>
<span id="cb26-300"><a href="#cb26-300" aria-hidden="true" tabindex="-1"></a><span class="in">likert_fit &lt;- likert::likert(likert_items_factor)</span></span>
<span id="cb26-301"><a href="#cb26-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-302"><a href="#cb26-302" aria-hidden="true" tabindex="-1"></a><span class="in"># Print the percentage table</span></span>
<span id="cb26-303"><a href="#cb26-303" aria-hidden="true" tabindex="-1"></a><span class="in">likert_fit$results</span></span>
<span id="cb26-304"><a href="#cb26-304" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-305"><a href="#cb26-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-306"><a href="#cb26-306" aria-hidden="true" tabindex="-1"></a><span class="fu">### Response Profile Plot</span></span>
<span id="cb26-307"><a href="#cb26-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-308"><a href="#cb26-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rq3-likert-plot, fig.width=10, fig.height=7}</span></span>
<span id="cb26-309"><a href="#cb26-309" aria-hidden="true" tabindex="-1"></a><span class="in">plot(likert_fit,type = "bar")</span></span>
<span id="cb26-310"><a href="#cb26-310" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-311"><a href="#cb26-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-312"><a href="#cb26-312" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-313"><a href="#cb26-313" aria-hidden="true" tabindex="-1"></a>**How to read this plot:** Each row is one survey item. The colored bar segments show the percentage of respondents choosing each comfort level. Items with a large "Mostly comfortable" segment (dark teal, far right) are tasks respondents feel confident about. Items with large segments on the left (uncomfortable) are where students may need more support or training.</span>
<span id="cb26-314"><a href="#cb26-314" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-315"><a href="#cb26-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-316"><a href="#cb26-316" aria-hidden="true" tabindex="-1"></a>::: {.note-box .jamovi}</span>
<span id="cb26-317"><a href="#cb26-317" aria-hidden="true" tabindex="-1"></a>In Jamovi, Install vijPlots module</span>
<span id="cb26-318"><a href="#cb26-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-319"><a href="#cb26-319" aria-hidden="true" tabindex="-1"></a>vijPlots -<span class="sc">\&gt;</span> Likert Plots -<span class="sc">\&gt;</span> select the nine Q1.2 sub-items (q1.2a through q1.2i) as "Items"</span>
<span id="cb26-320"><a href="#cb26-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-321"><a href="#cb26-321" aria-hidden="true" tabindex="-1"></a>Select the following options to create table and plot</span>
<span id="cb26-322"><a href="#cb26-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-323"><a href="#cb26-323" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/clipboard-900807379.png)</span></span>
<span id="cb26-324"><a href="#cb26-324" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-325"><a href="#cb26-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-326"><a href="#cb26-326" aria-hidden="true" tabindex="-1"></a>::: {.note-box .example}</span>
<span id="cb26-327"><a href="#cb26-327" aria-hidden="true" tabindex="-1"></a>**Reporting template (RQ3):**</span>
<span id="cb26-328"><a href="#cb26-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-329"><a href="#cb26-329" aria-hidden="true" tabindex="-1"></a>Descriptive analyses of the nine technology-comfort items (Q1.2) showed that mean ratings ranged from $M = 2.83$ ($SD = 0.99$) for *Downloading multimedia materials* to $M = 3.81$ ($SD = 0.68$) for *Using email* (see Table X). The Likert response profiles (Figure X) indicated that *Using email* had the highest concentration of "Mostly comfortable" responses (91.8%), whereas *Downloading multimedia materials* had the largest proportion of uncomfortable responses (35.0% combined across the two uncomfortable categories). These results suggest that students are generally comfortable with basic internet tasks (email, web access, keyboarding) but may need additional support with multimedia-related tasks such as downloading multimedia materials, viewing video, and listening to audio.</span>
<span id="cb26-330"><a href="#cb26-330" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-331"><a href="#cb26-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-332"><a href="#cb26-332" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb26-333"><a href="#cb26-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-334"><a href="#cb26-334" aria-hidden="true" tabindex="-1"></a><span class="fu">## RQ4: Logistic Regression — Predicting Willingness to Register Again</span></span>
<span id="cb26-335"><a href="#cb26-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-336"><a href="#cb26-336" aria-hidden="true" tabindex="-1"></a>**RQ4:** Which factors predict whether a respondent would consider registering for another online course if the topic was of interest?</span>
<span id="cb26-337"><a href="#cb26-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-338"><a href="#cb26-338" aria-hidden="true" tabindex="-1"></a>**Outcome variable (Q2.9):** Would you consider registering for another online course? (1 = Yes, 0 = No)</span>
<span id="cb26-339"><a href="#cb26-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-340"><a href="#cb26-340" aria-hidden="true" tabindex="-1"></a>**Predictor variables:**</span>
<span id="cb26-341"><a href="#cb26-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-342"><a href="#cb26-342" aria-hidden="true" tabindex="-1"></a>| Variable | Survey Question | Scale |</span>
<span id="cb26-343"><a href="#cb26-343" aria-hidden="true" tabindex="-1"></a>|:-------------------|:--------------------------------|:------------------|</span>
<span id="cb26-344"><a href="#cb26-344" aria-hidden="true" tabindex="-1"></a>| Q2.2 | Overall satisfaction with online course(s) taken | 1 (completely dissatisfied) – 6 (completely satisfied) |</span>
<span id="cb26-345"><a href="#cb26-345" aria-hidden="true" tabindex="-1"></a>| Q2.5 | Agreement that online courses meet the same quality standards as classroom courses | 1 (disagree) – 4 (agree) |</span>
<span id="cb26-346"><a href="#cb26-346" aria-hidden="true" tabindex="-1"></a>| Q1.3 | Motivation to learn more about using technology tools | 1 (poor) – 4 (excellent) |</span>
<span id="cb26-347"><a href="#cb26-347" aria-hidden="true" tabindex="-1"></a>| Q4.3 | Age range | 1 (youngest) – 5 (oldest) |</span>
<span id="cb26-348"><a href="#cb26-348" aria-hidden="true" tabindex="-1"></a>| Q4.4 | Distance from place of residence to the University | 1 (closest) – 5 (farthest) |</span>
<span id="cb26-349"><a href="#cb26-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-350"><a href="#cb26-350" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-351"><a href="#cb26-351" aria-hidden="true" tabindex="-1"></a>**Why logistic regression?** The outcome variable is binary (Yes / No). Ordinary linear regression is not appropriate for binary outcomes because it can predict values outside the 0–1 range. Logistic regression models the **log-odds** of the outcome and always produces predicted probabilities between 0 and 1.</span>
<span id="cb26-352"><a href="#cb26-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-353"><a href="#cb26-353" aria-hidden="true" tabindex="-1"></a>**What is an odds ratio (OR)?** The OR tells you how the *odds* of "Yes" change for each one-unit increase in a predictor:</span>
<span id="cb26-354"><a href="#cb26-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-355"><a href="#cb26-355" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>OR <span class="sc">\&gt;</span> 1: higher predictor values → higher odds of "Yes"</span>
<span id="cb26-356"><a href="#cb26-356" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>OR <span class="sc">\&lt;</span> 1: higher predictor values → lower odds of "Yes"</span>
<span id="cb26-357"><a href="#cb26-357" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>OR = 1: predictor has no effect on the odds</span>
<span id="cb26-358"><a href="#cb26-358" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>OR = 2: each one-unit increase *doubles* the odds of "Yes"</span>
<span id="cb26-359"><a href="#cb26-359" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-360"><a href="#cb26-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-361"><a href="#cb26-361" aria-hidden="true" tabindex="-1"></a><span class="fu">### Fit the Logistic Regression Model</span></span>
<span id="cb26-362"><a href="#cb26-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-363"><a href="#cb26-363" aria-hidden="true" tabindex="-1"></a><span class="in">`glm()`</span> fits a **Generalized Linear Model**. Setting <span class="in">`family = binomial(link = "logit")`</span> specifies logistic regression. The formula <span class="in">`register ~ ...`</span> reads: "predict register from the listed predictors."</span>
<span id="cb26-364"><a href="#cb26-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-365"><a href="#cb26-365" aria-hidden="true" tabindex="-1"></a><span class="in">```{r logit-fit}</span></span>
<span id="cb26-366"><a href="#cb26-366" aria-hidden="true" tabindex="-1"></a><span class="in">logit_model &lt;- glm(</span></span>
<span id="cb26-367"><a href="#cb26-367" aria-hidden="true" tabindex="-1"></a><span class="in">  q2.9 ~ q2.2 + q2.5 + q1.3 + q4.3 + q4.4,</span></span>
<span id="cb26-368"><a href="#cb26-368" aria-hidden="true" tabindex="-1"></a><span class="in">  data   = df,</span></span>
<span id="cb26-369"><a href="#cb26-369" aria-hidden="true" tabindex="-1"></a><span class="in">  family = binomial(link = "logit")</span></span>
<span id="cb26-370"><a href="#cb26-370" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-371"><a href="#cb26-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-372"><a href="#cb26-372" aria-hidden="true" tabindex="-1"></a><span class="in"># The summary shows log-odds coefficients (not yet odds ratios)</span></span>
<span id="cb26-373"><a href="#cb26-373" aria-hidden="true" tabindex="-1"></a><span class="in">summary(logit_model)</span></span>
<span id="cb26-374"><a href="#cb26-374" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-375"><a href="#cb26-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-376"><a href="#cb26-376" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model Summary Table (Odds Ratios)</span></span>
<span id="cb26-377"><a href="#cb26-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-378"><a href="#cb26-378" aria-hidden="true" tabindex="-1"></a><span class="in">`sjPlot::tab_model()`</span> exponentiates the log-odds coefficients to give **odds ratios** and displays them with 95% confidence intervals and p-values — all in one formatted table.</span>
<span id="cb26-379"><a href="#cb26-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-380"><a href="#cb26-380" aria-hidden="true" tabindex="-1"></a><span class="in">```{r logit-table}</span></span>
<span id="cb26-381"><a href="#cb26-381" aria-hidden="true" tabindex="-1"></a><span class="in">sjPlot::tab_model(</span></span>
<span id="cb26-382"><a href="#cb26-382" aria-hidden="true" tabindex="-1"></a><span class="in">  logit_model,</span></span>
<span id="cb26-383"><a href="#cb26-383" aria-hidden="true" tabindex="-1"></a><span class="in">  pred.labels = c(</span></span>
<span id="cb26-384"><a href="#cb26-384" aria-hidden="true" tabindex="-1"></a><span class="in">    "Intercept",</span></span>
<span id="cb26-385"><a href="#cb26-385" aria-hidden="true" tabindex="-1"></a><span class="in">    "Overall satisfaction (Q2.2)",</span></span>
<span id="cb26-386"><a href="#cb26-386" aria-hidden="true" tabindex="-1"></a><span class="in">    "Quality standards agreement (Q2.5)",</span></span>
<span id="cb26-387"><a href="#cb26-387" aria-hidden="true" tabindex="-1"></a><span class="in">    "Motivation for technology (Q1.3)",</span></span>
<span id="cb26-388"><a href="#cb26-388" aria-hidden="true" tabindex="-1"></a><span class="in">    "Age range (Q4.3)",</span></span>
<span id="cb26-389"><a href="#cb26-389" aria-hidden="true" tabindex="-1"></a><span class="in">    "Distance from university (Q4.4)"</span></span>
<span id="cb26-390"><a href="#cb26-390" aria-hidden="true" tabindex="-1"></a><span class="in">  ),</span></span>
<span id="cb26-391"><a href="#cb26-391" aria-hidden="true" tabindex="-1"></a><span class="in">  dv.labels = "Register for another online course (1 = Yes)",</span></span>
<span id="cb26-392"><a href="#cb26-392" aria-hidden="true" tabindex="-1"></a><span class="in">  digits    = 3</span></span>
<span id="cb26-393"><a href="#cb26-393" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-394"><a href="#cb26-394" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-395"><a href="#cb26-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-396"><a href="#cb26-396" aria-hidden="true" tabindex="-1"></a><span class="fu">### Odds Ratio Plot</span></span>
<span id="cb26-397"><a href="#cb26-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-398"><a href="#cb26-398" aria-hidden="true" tabindex="-1"></a>A forest plot displays each odds ratio as a dot with a horizontal line for its 95% confidence interval. If the line does **not** cross the vertical reference line at OR = 1, the predictor is statistically significant at $\alpha = .05$.</span>
<span id="cb26-399"><a href="#cb26-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-400"><a href="#cb26-400" aria-hidden="true" tabindex="-1"></a><span class="in">```{r logit-or-plot, fig.width=7, fig.height=4}</span></span>
<span id="cb26-401"><a href="#cb26-401" aria-hidden="true" tabindex="-1"></a><span class="in">sjPlot::plot_model(</span></span>
<span id="cb26-402"><a href="#cb26-402" aria-hidden="true" tabindex="-1"></a><span class="in">  logit_model,</span></span>
<span id="cb26-403"><a href="#cb26-403" aria-hidden="true" tabindex="-1"></a><span class="in">  type        = "est",</span></span>
<span id="cb26-404"><a href="#cb26-404" aria-hidden="true" tabindex="-1"></a><span class="in">  axis.labels = c(</span></span>
<span id="cb26-405"><a href="#cb26-405" aria-hidden="true" tabindex="-1"></a><span class="in">    "Distance from university (Q4.4)",</span></span>
<span id="cb26-406"><a href="#cb26-406" aria-hidden="true" tabindex="-1"></a><span class="in">    "Age range (Q4.3)",</span></span>
<span id="cb26-407"><a href="#cb26-407" aria-hidden="true" tabindex="-1"></a><span class="in">    "Motivation for technology (Q1.3)",</span></span>
<span id="cb26-408"><a href="#cb26-408" aria-hidden="true" tabindex="-1"></a><span class="in">    "Quality standards agreement (Q2.5)",</span></span>
<span id="cb26-409"><a href="#cb26-409" aria-hidden="true" tabindex="-1"></a><span class="in">    "Overall satisfaction (Q2.2)"</span></span>
<span id="cb26-410"><a href="#cb26-410" aria-hidden="true" tabindex="-1"></a><span class="in">  ),</span></span>
<span id="cb26-411"><a href="#cb26-411" aria-hidden="true" tabindex="-1"></a><span class="in">  title        = "Odds Ratios: Willingness to Register for Another Online Course",</span></span>
<span id="cb26-412"><a href="#cb26-412" aria-hidden="true" tabindex="-1"></a><span class="in">  show.values  = TRUE,</span></span>
<span id="cb26-413"><a href="#cb26-413" aria-hidden="true" tabindex="-1"></a><span class="in">  value.offset = 0.3</span></span>
<span id="cb26-414"><a href="#cb26-414" aria-hidden="true" tabindex="-1"></a><span class="in">)</span></span>
<span id="cb26-415"><a href="#cb26-415" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb26-416"><a href="#cb26-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-417"><a href="#cb26-417" aria-hidden="true" tabindex="-1"></a>::: {.note-box .jamovi}</span>
<span id="cb26-418"><a href="#cb26-418" aria-hidden="true" tabindex="-1"></a>In Jamovi, Analyses -<span class="sc">\&gt;</span> Regression -<span class="sc">\&gt;</span> Logistic Regression</span>
<span id="cb26-419"><a href="#cb26-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-420"><a href="#cb26-420" aria-hidden="true" tabindex="-1"></a>Select the following options to create table and plot</span>
<span id="cb26-421"><a href="#cb26-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-422"><a href="#cb26-422" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/clipboard-1013060150.png)</span></span>
<span id="cb26-423"><a href="#cb26-423" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/clipboard-527665642.png)</span></span>
<span id="cb26-424"><a href="#cb26-424" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-425"><a href="#cb26-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-426"><a href="#cb26-426" aria-hidden="true" tabindex="-1"></a>::: {.note-box .note}</span>
<span id="cb26-427"><a href="#cb26-427" aria-hidden="true" tabindex="-1"></a>**How to read this plot:**</span>
<span id="cb26-428"><a href="#cb26-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-429"><a href="#cb26-429" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Each **dot** is the estimated odds ratio for that predictor.</span>
<span id="cb26-430"><a href="#cb26-430" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The **horizontal line** through the dot is the 95% confidence interval.</span>
<span id="cb26-431"><a href="#cb26-431" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The **vertical dashed line** marks OR = 1 (no effect).</span>
<span id="cb26-432"><a href="#cb26-432" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If the entire CI is to the **right** of 1, the predictor significantly increases the odds of "Yes."</span>
<span id="cb26-433"><a href="#cb26-433" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If the entire CI is to the **left** of 1, the predictor significantly decreases the odds.</span>
<span id="cb26-434"><a href="#cb26-434" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>If the CI **crosses** 1, the predictor is not statistically significant at $\alpha = .05$.</span>
<span id="cb26-435"><a href="#cb26-435" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-436"><a href="#cb26-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-437"><a href="#cb26-437" aria-hidden="true" tabindex="-1"></a>::: {.note-box .example}</span>
<span id="cb26-438"><a href="#cb26-438" aria-hidden="true" tabindex="-1"></a>**Reporting template (RQ4):**</span>
<span id="cb26-439"><a href="#cb26-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-440"><a href="#cb26-440" aria-hidden="true" tabindex="-1"></a>A binary logistic regression was conducted to identify predictors of willingness to register for another online course ($N = 160$). Two predictors were statistically significant. Overall satisfaction with online coursework was a significant positive predictor (OR = 2.03, 95% CI <span class="sc">\[</span>1.25, 3.42<span class="sc">\]</span>, $p = .006$), indicating that each one-unit increase in satisfaction was associated with approximately twice the odds of willingness to register again. Agreement that online courses meet the same quality standards as classroom courses was also a significant positive predictor (OR = 2.62, 95% CI <span class="sc">\[</span>1.34, 5.70<span class="sc">\]</span>, $p = .008$). Motivation for technology use (OR = 0.81, 95% CI <span class="sc">\[</span>0.41, 1.55<span class="sc">\]</span>, $p = .529$), age range (OR = 1.17, 95% CI <span class="sc">\[</span>0.74, 2.12<span class="sc">\]</span>, $p = .539$), and distance from the university (OR = 0.94, 95% CI <span class="sc">\[</span>0.54, 1.69<span class="sc">\]</span>, $p = .829$) were not statistically significant predictors.</span>
<span id="cb26-441"><a href="#cb26-441" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb26-442"><a href="#cb26-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-443"><a href="#cb26-443" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb26-444"><a href="#cb26-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-445"><a href="#cb26-445" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary: What to Report</span></span>
<span id="cb26-446"><a href="#cb26-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-447"><a href="#cb26-447" aria-hidden="true" tabindex="-1"></a>| RQ | Method | Key statistics to report |</span>
<span id="cb26-448"><a href="#cb26-448" aria-hidden="true" tabindex="-1"></a>|:-----------------|:-----------------|:-----------------------------------|</span>
<span id="cb26-449"><a href="#cb26-449" aria-hidden="true" tabindex="-1"></a>| RQ1 | Frequency table + bar chart | *N*, % per category, combined satisfied/dissatisfied % |</span>
<span id="cb26-450"><a href="#cb26-450" aria-hidden="true" tabindex="-1"></a>| RQ2 | Chi-square + Cramer's *V* | $\chi^2$, df, *p*, Cramer's *V*, effect size interpretation |</span>
<span id="cb26-451"><a href="#cb26-451" aria-hidden="true" tabindex="-1"></a>| RQ3 | Likert response profile | Mean and SD per item; % in each response category |</span>
<span id="cb26-452"><a href="#cb26-452" aria-hidden="true" tabindex="-1"></a>| RQ4 | Binary logistic regression | OR with 95% CI and *p* per predictor |</span>
<span id="cb26-453"><a href="#cb26-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-454"><a href="#cb26-454" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercise</span></span>
<span id="cb26-455"><a href="#cb26-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-456"><a href="#cb26-456" aria-hidden="true" tabindex="-1"></a>Using the same data, answer the following research questions:</span>
<span id="cb26-457"><a href="#cb26-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-458"><a href="#cb26-458" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Describe where the primary computer is located for the participants in the sample (Q1.1)?</span>
<span id="cb26-459"><a href="#cb26-459" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>What's the relationship between whether they will recommend online courses to others (Q2.9) and their overall satisfaction with online courses (Q2.2)? Create a contingency table, chi-square test, and Cramer's *V* to answer this question. Then write a brief report summarizing the results.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>